In [5]:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, data type is different for both.

In [11]:
type(list_)

list

In [10]:
 

type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
for element in list_:
    print("Data type of element in list_:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>


In [13]:
for element in array_list:
    print("Data type of element in array_list:", type(element))


Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [14]:
array_list = np.array(object=list_, dtype=int)
for element in list_:
    print("Data type of element in list_:", type(element))
for element in array_list:
    print("Data type of element in array_list:", type(element))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [15]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [16]:
print("(i) Shape of num_array:", num_array.shape)

(i) Shape of num_array: (2, 3)


In [3]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
print("(ii) Size of num_array:", num_array.size)


(ii) Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [4]:
import numpy as np
zeros_array = np.zeros((3, 3))
print("3x3 matrix containing zeros only:\n", zeros_array)


3x3 matrix containing zeros only:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
